//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UICatel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Words
    {
        public long ID { get; set; }
        public string Word { get; set; }
        public decimal? Date { get; set; }
    }
}
